version: '2'
services:
    python:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        image: "tuananhbk/yolo"
        command: jupyter lab --ip=0.0.0.0 --port=8889 --NotebookApp.password='sha1:4018b457b8a9:84c65a176a549c58609c3cf38fa50b4b1b12b808'
