# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Tuple as typing___Tuple,
    Union as typing___Union,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class FileType(builtin___int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> 'FileType': ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List['FileType']: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, 'FileType']]: ...
    PNG = typing___cast('FileType', 0)
    JPG = typing___cast('FileType', 1)
PNG = typing___cast('FileType', 0)
JPG = typing___cast('FileType', 1)

class Size(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    width = ... # type: builtin___int
    heigh = ... # type: builtin___int

    def __init__(self,
        *,
        width : typing___Optional[builtin___int] = None,
        heigh : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Size: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Size: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"heigh",b"heigh",u"width",b"width"]) -> None: ...

class Metadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    image_format = ... # type: FileType

    @property
    def size(self) -> Size: ...

    def __init__(self,
        *,
        size : typing___Optional[Size] = None,
        image_format : typing___Optional[FileType] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Metadata: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Metadata: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"size",b"size"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"image_format",b"image_format",u"size",b"size"]) -> None: ...

class ImageMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    image = ... # type: builtin___bytes

    @property
    def meta(self) -> Metadata: ...

    def __init__(self,
        *,
        meta : typing___Optional[Metadata] = None,
        image : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ImageMessage: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ImageMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"image",b"image",u"meta",b"meta",u"test_oneof",b"test_oneof"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"image",b"image",u"meta",b"meta",u"test_oneof",b"test_oneof"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"test_oneof",b"test_oneof"]) -> typing_extensions___Literal["meta","image"]: ...

class Position(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    classId = ... # type: builtin___int
    left = ... # type: builtin___int
    top = ... # type: builtin___int
    right = ... # type: builtin___int
    bottom = ... # type: builtin___int

    def __init__(self,
        *,
        classId : typing___Optional[builtin___int] = None,
        left : typing___Optional[builtin___int] = None,
        top : typing___Optional[builtin___int] = None,
        right : typing___Optional[builtin___int] = None,
        bottom : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Position: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Position: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bottom",b"bottom",u"classId",b"classId",u"left",b"left",u"right",b"right",u"top",b"top"]) -> None: ...

class PositionsResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def position(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Position]: ...

    def __init__(self,
        *,
        position : typing___Optional[typing___Iterable[Position]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> PositionsResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> PositionsResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"position",b"position"]) -> None: ...
